[build]
  publish = "./tiramisu/site/rendered"
  command = "./build.sh"

[[redirects]]
  from = "https://main--tiramisu-hsp.netlify.app/*"
  to = "https://hsp-ec.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://tiramisu-hsp.netlify.app/*"
  to = "https://hsp-ec.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/fosstalks"
  to = "/announcements/fosstalks-2"
  status = 301
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "site/rendered"
  baseUrl = "https://hsp-ec.xyz"
  prettyURLs = true

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

 [plugins.inputs]
 baseUrl = "https://hsp-ec.xyz"
 sitemapPath = "/sitemap.xml"
 ignorePeriod = 0
 providers = ["google", "yandex"]

